### ISSUE TITLE
我想完善你的项目，操作系统六个实验我已经全部做完了，我看你两年都没更新了。

### ISSUE THREAD

**Issue by ghost** [cyicz123/HQU-CS-lab#1]
请给我一个授权，或者允许我在仓库中建立一个分支来进行修改。

以下是一些常见的授权方式：

给他人在你的仓库中建立分支：你可以在仓库设置中，将仓库的协作者添加为 Collaborators，这样他们就可以在你的仓库中建立分支并提交 pull request。

授权他人修改你的代码：你可以在你的仓库中接受 pull request，这样他人就可以向你的代码库提交修改，并等待你审核和合并他们的修改。

**Comment by cyicz123** [comment]
你好：
    非常欢迎你参与此项目的开源协作。您可以直接提交pr，我会合并入main分支中。
    祝你生活愉快~~~
